### ISSUE TITLE
Downloading Error

### ISSUE THREAD

**Issue by damare01** [mensch272/novelsave#37]
I get this error when I tried to download novels from foxaholic and chrysanthemumgarden
```
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\novelsave.exe\__main__.py", line 4, in <module>
  File "c:\program files\python39\lib\site-packages\novelsave\cli\__init__.py", line 1, in <module>
    from . import controllers
  File "c:\program files\python39\lib\site-packages\novelsave\cli\controllers\__init__.py", line 1, in <module>
    from ._update import update
  File "c:\program files\python39\lib\site-packages\novelsave\cli\controllers\_update.py", line 7, in <module>
    from .. import helpers
  File "c:\program files\python39\lib\site-packages\novelsave\cli\helpers\__init__.py", line 1, in <module>
    from .novel import get_novel, update_novel, download_thumbnail, download_chapters, download_assets, create_novel, get_or_create_novel
  File "c:\program files\python39\lib\site-packages\novelsave\cli\helpers\novel.py", line 12, in <module>
    from novelsave.cli.helpers.source import get_source_gateway
  File "c:\program files\python39\lib\site-packages\novelsave\cli\helpers\source.py", line 6, in <module>
    from novelsave.containers import Application
  File "c:\program files\python39\lib\site-packages\novelsave\containers.py", line 9, in <module>
    from novelsave.services.source import SourceService
  File "c:\program files\python39\lib\site-packages\novelsave\services\source\__init__.py", line 3, in <module>
    from .source_service import SourceService
  File "c:\program files\python39\lib\site-packages\novelsave\services\source\source_service.py", line 6, in <module>
    from novelsave_sources.utils import parse_source, parse_metasource
ImportError: cannot import name 'parse_source' from 'novelsave_sources.utils' (c:\program files\python39\lib\site-packages\novelsave_sources\utils\__init__.py)
```

**Comment by mensch272** [comment]
Totally my fault, I refactored `novelsave_sources` and didnt update `novelsave`. Lemme fix that real quick

**Comment by mensch272** [comment]
Fixed e8ae0c3bf8028fb9ee659a9b72371089e34282f2. Version `0.7.2` should fix the problem.

```bash
python -m pip install --upgrade novelsave
```

**Comment by damare01** [comment]
thank you!

**Comment by damare01** [comment]
another problem, download is not turning into epub. I checked the folder all I saw was the meta file.

**Comment by mensch272** [comment]
Thats weird. It works perfectly fine for me. Maybe you are checking the old source directories (looks like the link). The new source folders are named after their their title, for example Foxaholic and Chrysanthemum Garden

```
Packaged (type='epub', path='Foxaholic\...\...epub')
```

The default novels path is `~/novels`, so the epub would be saved in `~/novels/Foxaholic/.../...epub`.

**Comment by damare01** [comment]
thank u!
