### ISSUE TITLE
Railway

### ISSUE THREAD

**Issue by damare01** [mensch272/novelsave#66]
You should consider railway as an alternative for heroku. For me, I think it has more up time (dynos). I have tried deploying python repos on railway and majority of them works. It can also run repos with heroku built in it.

**Comment by mensch272** [comment]
The app will deploy to railway correctly now. It will use the dockerfile for build,

**Comment by damare01** [comment]
I tried deploying the bot on railway but I get this errors

`Traceback (most recent call last):
File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/app/novelsave/__main__.py", line 9, in <module>
discord.main()
File "/app/novelsave/client/bots/discord/main.py", line 25, in main
discord_application = wire([endpoints, session])
File "/app/novelsave/client/bots/discord/main.py", line 14, in wire
discord_application.wire(packages=packages)
File "src/dependency_injector/containers.pyx", line 317, in dependency_injector.containers.DynamicContainer.wire
File "/usr/local/lib/python3.9/site-packages/dependency_injector/wiring.py", line 361, in wire
_patch_attribute(cls, cls_member_name, cls_member, providers_map)
File "/usr/local/lib/python3.9/site-packages/dependency_injector/wiring.py", line 482, in _patch_attribute
instance = provider()
File "src/dependency_injector/providers.pyx", line 224, in dependency_injector.providers.Provider.__call__
File "src/dependency_injector/providers.pyx", line 2954, in dependency_injector.providers.Singleton._provide
File "src/dependency_injector/providers.pxd", line 645, in dependency_injector.providers.__factory_call
File "src/dependency_injector/providers.pxd", line 572, in dependency_injector.providers.__call
File "src/dependency_injector/providers.pxd", line 440, in dependency_injector.providers.__provide_keyword_args
File "src/dependency_injector/providers.pxd", line 360, in dependency_injector.providers.__get_value
File "src/dependency_injector/providers.pyx", line 224, in dependency_injector.providers.Provider.__call__
File "src/dependency_injector/providers.pyx", line 4149, in dependency_injector.providers.Selector._provide
dependency_injector.errors.Error: Selector has no "no  # disable search functionality" provider
Traceback (most recent call last):
File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/app/novelsave/__main__.py", line 9, in <module>
discord.main()
File "/app/novelsave/client/bots/discord/main.py", line 25, in main
discord_application = wire([endpoints, session])
File "/app/novelsave/client/bots/discord/main.py", line 14, in wire
discord_application.wire(packages=packages)
File "src/dependency_injector/containers.pyx", line 317, in dependency_injector.containers.DynamicContainer.wire
File "/usr/local/lib/python3.9/site-packages/dependency_injector/wiring.py", line 361, in wire
_patch_attribute(cls, cls_member_name, cls_member, providers_map)
File "/usr/local/lib/python3.9/site-packages/dependency_injector/wiring.py", line 482, in _patch_attribute
instance = provider()
File "src/dependency_injector/providers.pyx", line 224, in dependency_injector.providers.Provider.__call__
File "src/dependency_injector/providers.pyx", line 2954, in dependency_injector.providers.Singleton._provide
File "src/dependency_injector/providers.pxd", line 645, in dependency_injector.providers.__factory_call
File "src/dependency_injector/providers.pxd", line 572, in dependency_injector.providers.__call
File "src/dependency_injector/providers.pxd", line 440, in dependency_injector.providers.__provide_keyword_args
File "src/dependency_injector/providers.pxd", line 360, in dependency_injector.providers.__get_value
File "src/dependency_injector/providers.pyx", line 4149, in dependency_injector.providers.Selector._provide
File "src/dependency_injector/providers.pyx", line 224, in dependency_injector.providers.Provider.__call__
dependency_injector.errors.Error: Selector has no "no  # disable search functionality" provider
Traceback (most recent call last):
File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/app/novelsave/__main__.py", line 9, in <module>
discord.main()
File "/app/novelsave/client/bots/discord/main.py", line 25, in main
discord_application = wire([endpoints, session])
File "/app/novelsave/client/bots/discord/main.py", line 14, in wire
discord_application.wire(packages=packages)
File "src/dependency_injector/containers.pyx", line 317, in dependency_injector.containers.DynamicContainer.wire
File "/usr/local/lib/python3.9/site-packages/dependency_injector/wiring.py", line 361, in wire
_patch_attribute(cls, cls_member_name, cls_member, providers_map)
File "/usr/local/lib/python3.9/site-packages/dependency_injector/wiring.py", line 482, in _patch_attribute
instance = provider()
File "src/dependency_injector/providers.pyx", line 224, in dependency_injector.providers.Provider.__call__
File "src/dependency_injector/providers.pyx", line 2954, in dependency_injector.providers.Singleton._provide
File "src/dependency_injector/providers.pxd", line 645, in dependency_injector.providers.__factory_call
File "src/dependency_injector/providers.pxd", line 572, in dependency_injector.providers.__call
File "src/dependency_injector/providers.pxd", line 440, in dependency_injector.providers.__provide_keyword_args
File "src/dependency_injector/providers.pxd", line 360, in dependency_injector.providers.__get_value
File "src/dependency_injector/providers.pyx", line 224, in dependency_injector.providers.Provider.__call__
File "src/dependency_injector/providers.pyx", line 4149, in dependency_injector.providers.Selector._provide
dependency_injector.errors.Error: Selector has no "no  # disable search functionality" provider
Traceback (most recent call last):
File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/app/novelsave/__main__.py", line 9, in <module>
discord.main()
File "/app/novelsave/client/bots/discord/main.py", line 25, in main
discord_application = wire([endpoints, session])
File "/app/novelsave/client/bots/discord/main.py", line 14, in wire
discord_application.wire(packages=packages)
File "src/dependency_injector/containers.pyx", line 317, in dependency_injector.containers.DynamicContainer.wire
File "/usr/local/lib/python3.9/site-packages/dependency_injector/wiring.py", line 361, in wire
_patch_attribute(cls, cls_member_name, cls_member, providers_map)
File "/usr/local/lib/python3.9/site-packages/dependency_injector/wiring.py", line 482, in _patch_attribute
instance = provider()
File "src/dependency_injector/providers.pyx", line 224, in dependency_injector.providers.Provider.__call__
File "src/dependency_injector/providers.pyx", line 2954, in dependency_injector.providers.Singleton._provide
File "src/dependency_injector/providers.pxd", line 645, in dependency_injector.providers.__factory_call
File "src/dependency_injector/providers.pxd", line 572, in dependency_injector.providers.__call
File "src/dependency_injector/providers.pxd", line 440, in dependency_injector.providers.__provide_keyword_args
File "src/dependency_injector/providers.pxd", line 360, in dependency_injector.providers.__get_value
File "src/dependency_injector/providers.pyx", line 224, in dependency_injector.providers.Provider.__call__
File "src/dependency_injector/providers.pyx", line 4149, in dependency_injector.providers.Selector._provide
dependency_injector.errors.Error: Selector has no "no  # disable search functionality" provider`

**Comment by mensch272** [comment]
When you are setting the environment make sure to remove the comments

```
DISCORD_SEARCH_DISABLED=no
```

Instead of

```
DISCORD_SEARCH_DISABLED=no  # Disable search functionality
```

**Comment by damare01** [comment]
what does this mean?

`if channel.type is not ChannelType.private and channel.type is not ChannelType.group:
The above exception was the direct cause of the following exception:
nextcord.errors.ApplicationInvokeError: Command raised an exception: AttributeError: 'Object' object has no attribute 'type'`

**Comment by damare01** [comment]
bot won't reply to /dm command in group

**Comment by damare01** [comment]
> bot won't reply to /dm command in group

the other problems have been solve, thank you! This how do I solve this? The bot won't send direct message if a member send /dm

**Comment by mensch272** [comment]
Check to see if the bot has the appropriate permissions.

**Comment by damare01** [comment]
> Check to see if the bot has the appropriate permissions.
 I checked the send messages.

**Comment by mensch272** [comment]
I'll need more information before I can suggest anything else.

Below is the novelsave official bot's permissions in developer portal.
![Screenshot_20220329_042045](https://user-images.githubusercontent.com/47662901/160503068-648c2e1f-c1d2-4f97-9e25-d14c8ba55c42.png)

**Comment by damare01** [comment]
Thank you! It worked
